import { DM_Sans } from "next/font/google";

import "../globals.css";
import Header from "@/components/Header";

const dmSans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable} antialiased `}>
        <Header />
        <div className="pt-6 pb-3 px-6 max-w-[1280px] m-auto">{children}</div>
      </body>
    </html>
  );
}
